# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af281da88b79aa3a1a809e794ce5078787a0e45958046b10e1138d783ef1daa82fcea8161c7fc798d616dd8d5b2564504dd33b16b8ec6c6b8fea0bb45a31ad85

test:
  secret_key_base: fc6eb6e91755e5c82d09cc8ed81114d336965c741e786ee7e5e57c4b2c5263825fe63f24e19b23cd788461e282846f2ff97be4aa754d04a54bddd388b6e91626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
